spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /api


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  flyway:
    url: "${DATABASE_URL}"
    user: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:1234/k-agent-database
    username: myuser
    password: mypassword
  flyway:
    url: jdbc:postgresql://localhost:1234/k-agent-database
    user: myuser
    password: mypassword